### ISSUE TITLE
trainning our model counter the probelms

### ISSUE THREAD

**Issue by Zhang-hn1125** [jianlin-cheng/cryoten#2]
When I train the model using the new datasets, the command 
`python main.py fit`
output is
```
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: GET was unable to find an engine to execute this computation
```
How can I resolve it?

**Comment by joelselvaraj** [comment]
Hi, Thanks for trying CryoTEN. From what I have searched through the internet, the most common causes for this are:
1. Mismatch between `nvidia-smi`'s CUDA version and the CUDA version used by pytorch in the conda environment. Can you let me know what is your Nvidia graphics card model, NVIDIA driver version, CUDA version installed as observed from `nvidia-smi` command. You can try updating the nvidia driver and cuda version. CryoTEN is mostly trained and tested using CUDA 12.x version. 
2. Another reason this could happen is due to out of memory. In that case you can try reducing the batch size in `config/cryoten.yaml`. But we already use a very small default batch size of 4. So I am not sure if reducing will help.

**Comment by Zhang-hn1125** [comment]
Thank you for the suggestion and I have worked this problem. But I am encountering an issue during my model training process using PyTorch Lightning. Specifically, the training stops at epoch 5 with the following error message:
Epoch 5: 100%|████████████████████████████████████████| 22/22 [00:06<00:00,  3.64it/s, v_num=n3qz, train/loss_step=0.0138, train/loss_epoch=0.0241]
Traceback (most recent call last):
  File "/data3/cryoten/main.py", line 34, in <module>
    lightning_cli_run()
  File "/data3/cryoten/main.py", line 27, in lightning_cli_run
    cli = MyLightningCLI(save_config_callback=LoggerSaveConfigCallback, save_config_kwargs={"save_to_log_dir": False},
  File "/data2/anaconda3/envs/cryoten_env/lib/python3.11/site-packages/lightning/pytorch/cli.py", line 388, in __init__
    self._run_subcommand(self.subcommand)
  File "/data2/anaconda3/envs/cryoten_env/lib/python3.11/site-packages/lightning/pytorch/cli.py", line 679, in _run_subcommand
    fn(**fn_kwargs)
  File "/data2/anaconda3/envs/cryoten_env/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/data2/anaconda3/envs/cryoten_env/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data2/anaconda3/envs/cryoten_env/lib/python3.11/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data2/anaconda3/envs/cryoten_env/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/data2/anaconda3/envs/cryoten_env/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
  File "/data2/anaconda3/envs/cryoten_env/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1033, in _run_stage
    self.fit_loop.run()
  File "/data2/anaconda3/envs/cryoten_env/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 206, in run
    self.on_advance_end()
  File "/data2/anaconda3/envs/cryoten_env/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 386, in on_advance_end
    self.epoch_loop.update_lr_schedulers("epoch", update_plateau_schedulers=not self.restarting)
  File "/data2/anaconda3/envs/cryoten_env/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 349, in update_lr_schedulers
    self._update_learning_rates(interval=interval, update_plateau_schedulers=update_plateau_schedulers)
  File "/data2/anaconda3/envs/cryoten_env/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 384, in _update_learning_rates
    raise MisconfigurationException(
lightning.fabric.utilities.exceptions.MisconfigurationException: ReduceLROnPlateau conditioned on metric val/loss which is not available. Available metrics are: ['train/loss', 'train/loss_step', 'train/loss_epoch']. Condition can be set using `monitor` key in lr scheduler dict
How can I resolve it?

**Comment by joelselvaraj** [comment]
It looks the validation step that is supposed to run every 5 epochs didn't run for some reason. May I know the content of your `data/dataset.csv` file? and does it have entries for validation split? If no validation entries are present, it may skip the validation step leading to this error. This is my guess. You can also verify if the `data/dataset/` directory contains `train`, `val` subdirectories with input and target samples inside them.

**Comment by Zhang-hn1125** [comment]
Thank you very much, I have gone through these steps trainning by ourself. Good method, thank you for your suggestion.

**Comment by joelselvaraj** [comment]
That's great to know! I suppose this particular issue is solved? Can we close this issue? Always feel free to open new issues/reopen issues to discuss further.
